allowBuilds:
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@typescript-eslint/eslint-plugin@8.71.0'
  - '@typescript-eslint/parser@8.71.0'
  - '@typescript-eslint/type-utils@8.71.0'
  - '@typescript-eslint/utils@8.71.0'
  - browserslist@4.29.2
  - typescript-eslint@8.71.0
